import 'package:quiz_test/model/Level.dart';

class LevelRepository {
  // This will be generated by a JSON file later
  List<Level> generateLevelList() {
    return [
      Level(id: 1, name: 'Level 1'),
      Level(id: 2, name: 'Level 2'),
      Level(id: 3, name: 'Level 3'),
      Level(id: 4, name: 'Level 4'),
      Level(id: 5, name: 'Level 5'),
      Level(id: 6, name: 'Level 6'),
      Level(id: 7, name: 'Level 7'),
      Level(id: 8, name: 'Level 8'),
      Level(id: 9, name: 'Level 9'),
      Level(id: 10, name: 'Level 10'),
      Level(id: 11, name: 'Level 11'),
      Level(id: 12, name: 'Level 12'),
      Level(id: 13, name: 'Level 13'),
      Level(id: 14, name: 'Level 14'),
      Level(id: 15, name: 'Level 15'),
      Level(id: 16, name: 'Level 16'),
      Level(id: 17, name: 'Level 17'),
      Level(id: 18, name: 'Level 18'),
      Level(id: 19, name: 'Level 19'),
      Level(id: 20, name: 'Level 20')
    ];
  }
}
