import 'package:quiz_test/models/Answer.dart';

class AnswersRepository {
  // This will be generated by a JSON file later
  List<Answer> generateAnswerList(int level) {
    if (level == 1) {
      return [
        Answer(answer: 'mickey', imagePath: 'assets/images/levels/1/101.png'),
        Answer(answer: 'minnie', imagePath: 'assets/images/levels/1/102.png'),
        Answer(answer: 'goofy', imagePath: 'assets/images/levels/1/103.png'),
        Answer(answer: 'pluto', imagePath: 'assets/images/levels/1/104.png'),
        Answer(answer: 'ariel', imagePath: 'assets/images/levels/1/105.png'),
        Answer(answer: 'jasmine', imagePath: 'assets/images/levels/1/106.png'),
        Answer(
            answer: 'maleficent', imagePath: 'assets/images/levels/1/107.png'),
        Answer(answer: 'eeyore', imagePath: 'assets/images/levels/1/108.png'),
        Answer(answer: 'pooh', imagePath: 'assets/images/levels/1/109.png'),
        Answer(answer: 'tigger', imagePath: 'assets/images/levels/1/110.png'),
        Answer(answer: 'alice', imagePath: 'assets/images/levels/1/111.png'),
        Answer(answer: 'dumbo', imagePath: 'assets/images/levels/1/112.png'),
        Answer(answer: 'robin', imagePath: 'assets/images/levels/1/113.png'),
        Answer(answer: 'bambi', imagePath: 'assets/images/levels/1/114.png'),
        Answer(answer: 'thumper', imagePath: 'assets/images/levels/1/115.png'),
        Answer(answer: 'todd', imagePath: 'assets/images/levels/1/116.png'),
        Answer(answer: 'aladdin', imagePath: 'assets/images/levels/1/117.png'),
        Answer(answer: 'copper', imagePath: 'assets/images/levels/1/118.png')
      ];
    }

    if (level == 2) {
      return [
        Answer(answer: 'cruella', imagePath: 'assets/images/levels/2/201.png'),
        Answer(answer: 'darth', imagePath: 'assets/images/levels/2/202.png'),
        Answer(answer: 'stitch', imagePath: 'assets/images/levels/2/203.png'),
        Answer(answer: 'olaf', imagePath: 'assets/images/levels/2/204.png'),
        Answer(answer: 'anna', imagePath: 'assets/images/levels/2/205.png'),
        Answer(answer: 'lilo', imagePath: 'assets/images/levels/2/206.png'),
        Answer(answer: 'ralph', imagePath: 'assets/images/levels/2/207.png'),
        Answer(answer: 'forky', imagePath: 'assets/images/levels/2/208.png'),
        Answer(answer: 'buzz', imagePath: 'assets/images/levels/2/209.png'),
        Answer(answer: 'r2d2', imagePath: 'assets/images/levels/2/210.png'),
        Answer(answer: 'homer', imagePath: 'assets/images/levels/2/211.png'),
        Answer(answer: 'lisa', imagePath: 'assets/images/levels/2/212.png'),
        Answer(answer: 'krusty', imagePath: 'assets/images/levels/2/213.png'),
        Answer(answer: 'kermit', imagePath: 'assets/images/levels/2/214.png'),
        Answer(answer: 'gonzo', imagePath: 'assets/images/levels/2/215.png'),
        Answer(answer: 'jack', imagePath: 'assets/images/levels/2/216.png'),
        Answer(answer: 'mulan', imagePath: 'assets/images/levels/2/217.png'),
        Answer(answer: 'nemo', imagePath: 'assets/images/levels/2/218.png')
      ];
    }

    if (level == 3) {
      return [
        Answer(answer: 'mushu', imagePath: 'assets/images/levels/3/301.png'),
        Answer(answer: 'bolt', imagePath: 'assets/images/levels/3/302.png'),
        Answer(answer: 'boo', imagePath: 'assets/images/levels/3/303.png'),
        Answer(answer: 'jessie', imagePath: 'assets/images/levels/3/304.png'),
        Answer(answer: 'mater', imagePath: 'assets/images/levels/3/305.png'),
        Answer(answer: 'russell', imagePath: 'assets/images/levels/3/306.png'),
        Answer(
            answer: 'tinkerbell', imagePath: 'assets/images/levels/3/307.png'),
        Answer(answer: 'beast', imagePath: 'assets/images/levels/3/308.png'),
        Answer(answer: 'gaston', imagePath: 'assets/images/levels/3/309.png'),
        Answer(answer: 'rapunzel', imagePath: 'assets/images/levels/3/310.png'),
        Answer(answer: 'marge', imagePath: 'assets/images/levels/3/311.png'),
        Answer(answer: 'beaker', imagePath: 'assets/images/levels/3/312.png'),
        Answer(answer: 'animal', imagePath: 'assets/images/levels/3/313.png'),
        Answer(answer: 'moana', imagePath: 'assets/images/levels/3/314.png'),
        Answer(answer: 'wendy', imagePath: 'assets/images/levels/3/315.png'),
        Answer(answer: 'mowgli', imagePath: 'assets/images/levels/3/316.png'),
        Answer(answer: 'marie', imagePath: 'assets/images/levels/3/317.png'),
        Answer(answer: 'remy', imagePath: 'assets/images/levels/3/318.png')
      ];
    }

    return [];
  }
}
